export interface plcData{
    "t_prod": number,
    "t_smoke": number,
    "sp_max_t": number,
    "dp": number,
    "sp_dp_min": number,
    "drum": boolean,
    "mixer": boolean,
    "drum_speed": number,
    "smoke_fan_speed": number,
    "cooler": boolean,
    "cooler_speed": number,
    "fire": boolean,
    "t_box": number,
    "plc_work_time": number,
    "ror": number,
    "gaz_start": number,
    "gaz1": number,
    "gaz2": number,
    "gaz3": number,
    "gaz4": number,
    "gaz5": number,
    "gaz6": number,
    "gaz7": number,
    "gaz8": number,
    "gaz9": number,
    "gaz10": number,
    "gaz_preset": number,
    // "pid_kp": number,
    // "pid_ti": number,
    // "pid_out": number,
    "alarm": boolean,
    "connected": boolean,
    "alarms": [{
        "id": number,
        "title": string,
        "state": boolean
    }]
}